name: CMake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        qt-version: [5.15.2]
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
        choco install -y strawberryperl python visualstudio2022buildtools visualstudio2022-workload-vctools ninja cmake git
        choco install -y visualstudio2019buildtools # In case you need specific version

    - name: Add Visual Studio to PATH
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        setx PATH "%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\*\bin\Hostx64\x64"
        
    - name: Install Visual Studio Build Tools
      if: matrix.os == 'windows-latest'
      run: |
        choco install -y visualstudio2022buildtools
        choco install -y visualstudio2022-workload-vctools


    - name: Add Visual Studio to PATH
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        setx PATH "%PATH%;C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\*\bin\Hostx64\x64"
        
    - name: Verify nmake availability
      if: matrix.os == 'windows-latest'
      run: where nmake
      
    - name: Set up MSVC environment
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
        where nmake

    - name: Add nmake to PATH
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        echo "Adding Visual Studio paths..."
        VS_PATH=$(vswhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath)
        echo "VS_PATH=$VS_PATH"
        if [ -d "$VS_PATH" ]; then
          echo "$VS_PATH/VC/Tools/MSVC/*/bin/Hostx64/x64" >> $GITHUB_PATH
        else
          echo "Visual Studio installation not found!"
          exit 1
        fi

    - name: Debug PATH
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: echo %PATH%

    - name: Check if nmake is installed
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: where nmake || echo "nmake not found"

    - name: Download Qt source code on Windows
      if: matrix.os == 'windows-latest'
      run: |
        curl -L -o qt-everywhere-src-5.15.2.zip https://download.qt.io/official_releases/qt/5.15/5.15.2/single/qt-everywhere-src-5.15.2.zip
        tar -xf qt-everywhere-src-5.15.2.zip

    - name: Configure Qt build on Windows
      if: matrix.os == 'windows-latest'
      run: |
        cd qt-everywhere-src-5.15.2
        mkdir build
        cd build
        ..\configure -platform win32-msvc -opensource -confirm-license -release -nomake tests -nomake examples

    - name: Build Qt on Windows
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat" x64
        cd qt-everywhere-src-5.15.2\build
        nmake


    - name: Install Qt on Windows
      if: matrix.os == 'windows-latest'
      run: |
        cd qt-everywhere-src-5.15.2\build
        nmake install

    - name: Install Qt on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

    - name: Install OpenCV on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libopencv-dev

    - name: Install OpenCV on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install -y opencv
        Move-Item -Path "C:/tools/opencv" -Destination "C:/opencv"

    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
