name: CMake on multiple platforms

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        qt-version: [5.15.2]
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Cache CMake build files
      uses: actions/cache@v3
      with:
        path: ${{ steps.strings.outputs.build-output-dir }}
        key: ${{ runner.os }}-cmake-${{ matrix.c_compiler }}-${{ matrix.build_type }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-${{ matrix.c_compiler }}-${{ matrix.build_type }}-

    - name: Cache APT packages
      if: matrix.os == 'ubuntu-latest'
      uses: actions/cache@v3
      with:
        path: |
          /var/cache/apt/archives/*.deb
        key: ubuntu-apt-${{ matrix.os }}-${{ matrix.c_compiler }}-${{ matrix.build_type }}-${{ hashFiles('.github/workflows/**') }}
        restore-keys: |
          ubuntu-apt-${{ matrix.os }}-${{ matrix.c_compiler }}-${{ matrix.build_type }}-
          ubuntu-apt-${{ matrix.os }}-${{ matrix.c_compiler }}-
          ubuntu-apt-${{ matrix.os }}-
          ubuntu-apt-


    - name: Install dependencies on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install -y strawberryperl python visualstudio2022buildtools visualstudio2022-workload-vctools ninja cmake git aqt

    - name: Cache Qt AQT installation (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v3
      with:
        path: 5.15.2
        key: windows-qt-5.15.2

    - name: Install Qt on Windows
      if: matrix.os == 'windows-latest'
      run: |
        aqt install-qt windows desktop 5.15.2 win64_msvc2019_64

    - name: Install Qt on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools

    - name: Install OpenCV on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y libopencv-dev

    - name: Cache OpenCV binaries (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/cache@v3
      with:
        path: C:/opencv
        key: windows-opencv

    - name: Install OpenCV on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install -y opencv
        Move-Item -Path "C:/tools/opencv" -Destination "C:/opencv"

    - name: Configure CMake for Windows
      if: matrix.os == 'windows-latest'
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_PREFIX_PATH=D:\a\APO-Lab-App\APO-Lab-App\5.15.2\msvc2019_64\lib\cmake
      env:
        QT_DIR: D:\a\APO-Lab-App\APO-Lab-App\5.15.2\msvc2019_64\lib\cmake

    - name: Configure CMake for Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
              -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
              -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
